// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJRjadWATqcphje8n8h8X0Rav5iN2B_ek',
    appId: '1:117385232890:web:3a3302db8c52c738cf2443',
    messagingSenderId: '117385232890',
    projectId: 'poojashop-100ad',
    authDomain: 'poojashop-100ad.firebaseapp.com',
    storageBucket: 'poojashop-100ad.appspot.com',
    measurementId: 'G-EV1KZDM5TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7fzlptpKiecPNb4LX6wGIjZb5NBeDtLg',
    appId: '1:117385232890:android:c3421faa65b8e4c3cf2443',
    messagingSenderId: '117385232890',
    projectId: 'poojashop-100ad',
    storageBucket: 'poojashop-100ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSe3fG6oGsRodyQHDZMctORoEeRJjCcTU',
    appId: '1:117385232890:ios:761b89a608c75b35cf2443',
    messagingSenderId: '117385232890',
    projectId: 'poojashop-100ad',
    storageBucket: 'poojashop-100ad.appspot.com',
    iosClientId: '117385232890-5kifj6vlelneqcc008clmo80pahdeo1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.poojaShop',
  );
}
